/** Salon control panel toggle keys (CLAUDE.md) */
export const SETTINGS_KEYS = {
  online_booking_enabled: 'online_booking_enabled',
  auto_confirm_booking: 'auto_confirm_booking',
  booking_advance_days: 'booking_advance_days',
  min_booking_notice_hours: 'min_booking_notice_hours',
  cancellation_deadline_hours: 'cancellation_deadline_hours',
  max_daily_bookings: 'max_daily_bookings',
  walk_in_enabled: 'walk_in_enabled',
  vacation_mode: 'vacation_mode',
  vacation_message_ar: 'vacation_message_ar',
  vacation_start_date: 'vacation_start_date',
  vacation_end_date: 'vacation_end_date',
  whatsapp_enabled: 'whatsapp_enabled',
  whatsapp_token: 'whatsapp_token',
  whatsapp_phone_number_id: 'whatsapp_phone_number_id',
  whatsapp_business_name: 'whatsapp_business_name',
  whatsapp_verified: 'whatsapp_verified',
  sms_enabled: 'sms_enabled',
  email_enabled: 'email_enabled',
  whatsapp_booking_confirm: 'whatsapp_booking_confirm',
  whatsapp_booking_reminder: 'whatsapp_booking_reminder',
  whatsapp_invoice_send: 'whatsapp_invoice_send',
  whatsapp_review_request: 'whatsapp_review_request',
  loyalty_enabled: 'loyalty_enabled',
  coupons_enabled: 'coupons_enabled',
  onboarding_completed: 'onboarding_completed',
} as const;

export const SETTINGS_DEFAULTS: Record<string, string> = {
  [SETTINGS_KEYS.online_booking_enabled]: 'true',
  [SETTINGS_KEYS.auto_confirm_booking]: 'false',
  [SETTINGS_KEYS.booking_advance_days]: '30',
  [SETTINGS_KEYS.min_booking_notice_hours]: '2',
  [SETTINGS_KEYS.cancellation_deadline_hours]: '12',
  [SETTINGS_KEYS.max_daily_bookings]: '0',
  [SETTINGS_KEYS.walk_in_enabled]: 'true',
  [SETTINGS_KEYS.vacation_mode]: 'false',
  [SETTINGS_KEYS.vacation_message_ar]: '',
  [SETTINGS_KEYS.vacation_start_date]: '',
  [SETTINGS_KEYS.vacation_end_date]: '',
  [SETTINGS_KEYS.whatsapp_enabled]: 'true',
  [SETTINGS_KEYS.whatsapp_token]: '',
  [SETTINGS_KEYS.whatsapp_phone_number_id]: '',
  [SETTINGS_KEYS.whatsapp_business_name]: '',
  [SETTINGS_KEYS.whatsapp_verified]: 'false',
  [SETTINGS_KEYS.sms_enabled]: 'false',
  [SETTINGS_KEYS.email_enabled]: 'true',
  [SETTINGS_KEYS.whatsapp_booking_confirm]: 'true',
  [SETTINGS_KEYS.whatsapp_booking_reminder]: 'true',
  [SETTINGS_KEYS.whatsapp_invoice_send]: 'true',
  [SETTINGS_KEYS.whatsapp_review_request]: 'true',
  [SETTINGS_KEYS.loyalty_enabled]: 'true',
  [SETTINGS_KEYS.coupons_enabled]: 'true',
};
