/** Salon control panel toggle keys (CLAUDE.md) */
export const SETTINGS_KEYS = {
  online_booking_enabled: 'online_booking_enabled',
  auto_confirm_booking: 'auto_confirm_booking',
  booking_advance_days: 'booking_advance_days',
  min_booking_notice_hours: 'min_booking_notice_hours',
  cancellation_deadline_hours: 'cancellation_deadline_hours',
  max_daily_bookings: 'max_daily_bookings',
  walk_in_enabled: 'walk_in_enabled',
  vacation_mode: 'vacation_mode',
  vacation_message_ar: 'vacation_message_ar',
  vacation_start_date: 'vacation_start_date',
  vacation_end_date: 'vacation_end_date',
  whatsapp_enabled: 'whatsapp_enabled',
  whatsapp_token: 'whatsapp_token',
  whatsapp_phone_number_id: 'whatsapp_phone_number_id',
  whatsapp_business_name: 'whatsapp_business_name',
  whatsapp_verified: 'whatsapp_verified',
  sms_enabled: 'sms_enabled',
  email_enabled: 'email_enabled',
  whatsapp_booking_confirm: 'whatsapp_booking_confirm',
  whatsapp_booking_reminder: 'whatsapp_booking_reminder',
  whatsapp_invoice_send: 'whatsapp_invoice_send',
  whatsapp_review_request: 'whatsapp_review_request',
  // ═══════ WhatsApp Evolution API (anti-ban + provider) ═══════
  whatsapp_provider: 'whatsapp_provider',
  whatsapp_business_hours_enabled: 'whatsapp_business_hours_enabled',
  whatsapp_business_hours_start: 'whatsapp_business_hours_start',
  whatsapp_business_hours_end: 'whatsapp_business_hours_end',
  whatsapp_rate_limit_per_hour: 'whatsapp_rate_limit_per_hour',
  whatsapp_random_delay_min_ms: 'whatsapp_random_delay_min_ms',
  whatsapp_random_delay_max_ms: 'whatsapp_random_delay_max_ms',
  whatsapp_marketing_enabled: 'whatsapp_marketing_enabled',

  // ═══════ AI Reception ═══════
  ai_reception_enabled: 'ai_reception_enabled',
  ai_manager_phone: 'ai_manager_phone',
  ai_tone: 'ai_tone',
  ai_welcome_message: 'ai_welcome_message',
  ai_approval_timeout_minutes: 'ai_approval_timeout_minutes',
  ai_max_understanding_failures: 'ai_max_understanding_failures',
  ai_escalation_cooldown_minutes: 'ai_escalation_cooldown_minutes',
  ai_booking_confirmation_mode: 'ai_booking_confirmation_mode',
  ai_privacy_message_enabled: 'ai_privacy_message_enabled',
  ai_privacy_message: 'ai_privacy_message',
  ai_avoided_phrases: 'ai_avoided_phrases',
  ai_custom_escalation_keywords: 'ai_custom_escalation_keywords',
  ai_show_employee_names_to_customers: 'ai_show_employee_names_to_customers',
  ai_available_slots_limit: 'ai_available_slots_limit',

  // Post-visit review and reputation
  review_request_enabled: 'review_request_enabled',
  review_request_delay_minutes: 'review_request_delay_minutes',
  google_review_url: 'google_review_url',
  low_rating_threshold: 'low_rating_threshold',
  high_rating_threshold: 'high_rating_threshold',
  review_request_message: 'review_request_message',
  low_rating_response_message: 'low_rating_response_message',
  high_rating_response_message: 'high_rating_response_message',

  loyalty_enabled: 'loyalty_enabled',
  coupons_enabled: 'coupons_enabled',
  onboarding_completed: 'onboarding_completed',

  // ═══════ Branding / Theme ═══════
  dashboard_theme: 'dashboard_theme',
  dashboard_mode: 'dashboard_mode',
  seasonal_themes_enabled: 'seasonal_themes_enabled',
} as const;

export const SETTINGS_DEFAULTS: Record<string, string> = {
  [SETTINGS_KEYS.online_booking_enabled]: 'true',
  [SETTINGS_KEYS.auto_confirm_booking]: 'false',
  [SETTINGS_KEYS.booking_advance_days]: '30',
  [SETTINGS_KEYS.min_booking_notice_hours]: '2',
  [SETTINGS_KEYS.cancellation_deadline_hours]: '12',
  [SETTINGS_KEYS.max_daily_bookings]: '0',
  [SETTINGS_KEYS.walk_in_enabled]: 'true',
  [SETTINGS_KEYS.vacation_mode]: 'false',
  [SETTINGS_KEYS.vacation_message_ar]: '',
  [SETTINGS_KEYS.vacation_start_date]: '',
  [SETTINGS_KEYS.vacation_end_date]: '',
  [SETTINGS_KEYS.whatsapp_enabled]: 'true',
  [SETTINGS_KEYS.whatsapp_token]: '',
  [SETTINGS_KEYS.whatsapp_phone_number_id]: '',
  [SETTINGS_KEYS.whatsapp_business_name]: '',
  [SETTINGS_KEYS.whatsapp_verified]: 'false',
  [SETTINGS_KEYS.sms_enabled]: 'false',
  [SETTINGS_KEYS.email_enabled]: 'true',
  [SETTINGS_KEYS.whatsapp_booking_confirm]: 'true',
  [SETTINGS_KEYS.whatsapp_booking_reminder]: 'true',
  [SETTINGS_KEYS.whatsapp_invoice_send]: 'true',
  [SETTINGS_KEYS.whatsapp_review_request]: 'true',
  [SETTINGS_KEYS.whatsapp_provider]: 'evolution',
  [SETTINGS_KEYS.whatsapp_business_hours_enabled]: 'true',
  [SETTINGS_KEYS.whatsapp_business_hours_start]: '09:00',
  [SETTINGS_KEYS.whatsapp_business_hours_end]: '22:00',
  [SETTINGS_KEYS.whatsapp_rate_limit_per_hour]: '30',
  [SETTINGS_KEYS.whatsapp_random_delay_min_ms]: '1500',
  [SETTINGS_KEYS.whatsapp_random_delay_max_ms]: '4500',
  [SETTINGS_KEYS.whatsapp_marketing_enabled]: 'true',
  [SETTINGS_KEYS.ai_reception_enabled]: 'true',
  [SETTINGS_KEYS.ai_manager_phone]: '',
  [SETTINGS_KEYS.ai_tone]: 'light_gulf',
  [SETTINGS_KEYS.ai_welcome_message]: 'حياك الله، كيف أقدر أساعدك؟ للحجز أو الأسعار أو تعديل موعد.',
  [SETTINGS_KEYS.ai_approval_timeout_minutes]: '15',
  [SETTINGS_KEYS.ai_max_understanding_failures]: '2',
  [SETTINGS_KEYS.ai_escalation_cooldown_minutes]: '10',
  [SETTINGS_KEYS.ai_booking_confirmation_mode]: 'manual',
  [SETTINGS_KEYS.ai_privacy_message_enabled]: 'false',
  [SETTINGS_KEYS.ai_privacy_message]: 'سيتم استخدام بياناتك فقط لإدارة الحجز والتواصل بخصوص الموعد.',
  [SETTINGS_KEYS.ai_avoided_phrases]: 'حبيبتي\nالغالية',
  [SETTINGS_KEYS.ai_custom_escalation_keywords]: '',
  [SETTINGS_KEYS.ai_show_employee_names_to_customers]: 'false',
  [SETTINGS_KEYS.ai_available_slots_limit]: '3',
  [SETTINGS_KEYS.review_request_enabled]: 'false',
  [SETTINGS_KEYS.review_request_delay_minutes]: '60',
  [SETTINGS_KEYS.google_review_url]: '',
  [SETTINGS_KEYS.low_rating_threshold]: '3',
  [SETTINGS_KEYS.high_rating_threshold]: '4',
  [SETTINGS_KEYS.review_request_message]: 'نسعد بمعرفة تقييمك لتجربتك من 1 إلى 5.',
  [SETTINGS_KEYS.low_rating_response_message]: 'نعتذر عن تجربتك. تم رفع ملاحظتك للإدارة لتحسين الخدمة.',
  [SETTINGS_KEYS.high_rating_response_message]: 'شكرًا لتقييمك. يسعدنا دعمك بتقييمنا على Google: [googleReviewUrl]',
  [SETTINGS_KEYS.loyalty_enabled]: 'true',
  [SETTINGS_KEYS.coupons_enabled]: 'true',
  [SETTINGS_KEYS.dashboard_theme]: 'velvet',
  [SETTINGS_KEYS.dashboard_mode]: 'light',
  [SETTINGS_KEYS.seasonal_themes_enabled]: 'true',
};
