apiVersion: v1
kind: Service
metadata:
  name: servix-api
  namespace: servix
  labels:
    app: servix-api
spec:
  selector:
    app: servix-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
