import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

/**
 * V-60 — Body shape for `POST /auth/verify-reset-token`.
 *
 * Use case: the frontend's reset-password page calls this BEFORE
 * showing the password-entry form, to verify that the token from
 * the email URL is still valid + non-expired + non-used. A separate
 * `POST /auth/reset-password` (see [[ResetPasswordDto]]) actually
 * sets the new password.
 *
 * The `token` field is the raw 36-char UUID generated by V-24's
 * (and self-serve's) reset flow — hashed server-side and compared
 * to `password_resets.token` (which stores sha256 hex).
 */
export class VerifyResetTokenDto {
  @ApiProperty({ description: 'رمز إعادة التعيين المُستلَم في رابط البريد' })
  @IsNotEmpty({ message: 'رمز إعادة التعيين مطلوب' })
  @IsString({ message: 'الرمز يجب أن يكون نصاً' })
  token: string;
}
