-- No-op: salary column and expense.employee_id already exist in baseline.
-- This migration is kept as an empty placeholder to preserve the migration
-- history sequence (prisma tracks applied migrations by name).
