apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: servix
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: pgbouncer
      port: 6432
      targetPort: 6432
  clusterIP: None  # Headless for StatefulSet
