-- ════════════════════════════════════════════════════════════════════
-- V-18 / A1-006 — Missing FK indices on tenant tables
-- Source: docs/principal-audit/synthesis-2026-05-14.md (HIGH P1)
-- ────────────────────────────────────────────────────────────────────
-- Adds covering indices for foreign-key columns that are joined frequently
-- but currently force sequential scans. Each statement is idempotent
-- (IF NOT EXISTS) and runs inside the migration's transaction.
--
-- Index-build strategy (see V-77+): plain CREATE INDEX — instant on the empty
-- tenant DBs that `prisma migrate deploy` targets, so CONCURRENTLY buys
-- nothing there. To add these to an EXISTING POPULATED tenant without locking
-- writes, build them OUT-OF-BAND FIRST (then migrate deploy is a no-op via
-- IF NOT EXISTS), each on its own psql -c call (CONCURRENTLY needs autocommit):
--   psql "$TENANT_DATABASE_URL" -c 'CREATE INDEX CONCURRENTLY IF NOT EXISTS "appointment_services_service_id_idx" ON "appointment_services"("service_id");'
--   psql "$TENANT_DATABASE_URL" -c 'CREATE INDEX CONCURRENTLY IF NOT EXISTS "appointment_services_employee_id_idx" ON "appointment_services"("employee_id");'
--   psql "$TENANT_DATABASE_URL" -c 'CREATE INDEX CONCURRENTLY IF NOT EXISTS "invoice_items_service_id_idx" ON "invoice_items"("service_id");'
-- These were CONCURRENTLY in-file until V-77+; removed because Prisma sends a
-- no-transaction migration as one multi-statement string, which Postgres runs
-- in an implicit transaction — and CONCURRENTLY is forbidden inside a tx.
--
-- Apply via the runbook: docs/migrations/v18-fk-indices-apply.md
-- ════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS "appointment_services_service_id_idx"
  ON "appointment_services"("service_id");

CREATE INDEX IF NOT EXISTS "appointment_services_employee_id_idx"
  ON "appointment_services"("employee_id");

CREATE INDEX IF NOT EXISTS "invoice_items_service_id_idx"
  ON "invoice_items"("service_id");

-- ────────────────────────────────────────────────────────────────────
-- Rollback (manual, not auto-generated by Prisma):
--   DROP INDEX IF EXISTS "appointment_services_service_id_idx";
--   DROP INDEX IF EXISTS "appointment_services_employee_id_idx";
--   DROP INDEX IF EXISTS "invoice_items_service_id_idx";
-- (On a populated tenant, prefer DROP INDEX CONCURRENTLY IF EXISTS … via psql,
--  each on its own psql -c call.)
-- ════════════════════════════════════════════════════════════════════
