-- prisma+migrate:no-transaction
-- ════════════════════════════════════════════════════════════════════
-- V-18 / A1-006 — Missing FK indices on tenant tables
-- Source: docs/principal-audit/synthesis-2026-05-14.md (HIGH P1)
-- ────────────────────────────────────────────────────────────────────
-- Adds covering indices for foreign-key columns that are joined frequently
-- but currently force sequential scans. Each statement is idempotent.
--
-- Apply via the runbook: docs/migrations/v18-fk-indices-apply.md
-- Note: CONCURRENTLY cannot run inside a transaction; the directive above
-- tells Prisma migrate to execute these statements outside a tx block.
-- ════════════════════════════════════════════════════════════════════

CREATE INDEX CONCURRENTLY IF NOT EXISTS "appointment_services_service_id_idx"
  ON "appointment_services"("service_id");

CREATE INDEX CONCURRENTLY IF NOT EXISTS "appointment_services_employee_id_idx"
  ON "appointment_services"("employee_id");

CREATE INDEX CONCURRENTLY IF NOT EXISTS "invoice_items_service_id_idx"
  ON "invoice_items"("service_id");

-- ────────────────────────────────────────────────────────────────────
-- Rollback (manual, not auto-generated by Prisma):
--   DROP INDEX CONCURRENTLY IF EXISTS "appointment_services_service_id_idx";
--   DROP INDEX CONCURRENTLY IF EXISTS "appointment_services_employee_id_idx";
--   DROP INDEX CONCURRENTLY IF EXISTS "invoice_items_service_id_idx";
-- ════════════════════════════════════════════════════════════════════
