import { Injectable } from '@nestjs/common';
import { hash, compare } from 'bcryptjs';
import { PlatformPrismaClient } from '../../shared/database/platform.client';

// V-42 — same cost factor as password hashing (auth.service BCRYPT_ROUNDS),
// per owner directive (consistency). Keep in sync if the password cost moves.
const BACKUP_CODE_BCRYPT_ROUNDS = 12;

/**
 * V-42 — single-use 2FA backup (recovery) codes.
 *
 * Codes are generated by TwoFactorService.generateBackupCodes (CSPRNG via
 * crypto.randomBytes), bcrypt-hashed here, and stored one-row-per-code. They
 * are inert until 2FA is enabled (verifyAndConsume is only reachable through
 * verify2FALogin, which requires twoFactorEnabled). Recovery compares the
 * input against each UNUSED row and consumes the match via an atomic guarded
 * UPDATE, so two concurrent requests can never spend the same code.
 */
@Injectable()
export class TwoFactorBackupCodeService {
  constructor(private readonly prisma: PlatformPrismaClient) {}

  /** Canonical form: codes are stored/compared upper-cased and trimmed. */
  private normalize(code: string): string {
    return code.trim().toUpperCase();
  }

  /**
   * Hash + replace the user's entire code set (delete old, insert new) in one
   * transaction. Returns nothing — the caller owns surfacing the PLAINTEXT
   * codes to the user exactly once.
   */
  async store(userId: string, plaintextCodes: string[]): Promise<void> {
    const rows = await Promise.all(
      plaintextCodes.map(async (c) => ({
        userId,
        codeHash: await hash(this.normalize(c), BACKUP_CODE_BCRYPT_ROUNDS),
      })),
    );
    await this.prisma.$transaction([
      this.prisma.twoFactorBackupCode.deleteMany({ where: { userId } }),
      this.prisma.twoFactorBackupCode.createMany({ data: rows }),
    ]);
  }

  /**
   * Verify `code` against the user's UNUSED codes; on match, atomically
   * consume it (single-use, race-safe) and return true. False otherwise.
   *
   * The `updateMany … where: { id, usedAt: null }` is the atomic guard: of N
   * concurrent requests presenting the same valid code, exactly one UPDATE
   * matches a still-null row (count === 1) and wins; the rest get count === 0.
   */
  async verifyAndConsume(userId: string, code: string): Promise<boolean> {
    const candidate = this.normalize(code);
    const unused = await this.prisma.twoFactorBackupCode.findMany({
      where: { userId, usedAt: null },
      select: { id: true, codeHash: true },
    });
    for (const row of unused) {
      if (await compare(candidate, row.codeHash)) {
        const { count } = await this.prisma.twoFactorBackupCode.updateMany({
          where: { id: row.id, usedAt: null },
          data: { usedAt: new Date() },
        });
        return count === 1;
      }
    }
    return false;
  }

  /** Remove all of a user's codes — called on 2FA disable (no stale vector). */
  async deleteAll(userId: string): Promise<void> {
    await this.prisma.twoFactorBackupCode.deleteMany({ where: { userId } });
  }

  /** Remaining unused codes (for "N codes left" UX / audit metadata). */
  async countUnused(userId: string): Promise<number> {
    return this.prisma.twoFactorBackupCode.count({
      where: { userId, usedAt: null },
    });
  }
}
